# Generated by Django 6.0 on 2026-01-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
